steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-m', '30g', '-t', 'gcr.io/scpworkshop/cornell_sc_workshop:alpha', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/scpworkshop/cornell_sc_workshop:alpha']
options:
  machineType: 'N2_HIGHCPU_32'
timeout: 9600s